# Generated by Django 2.1.7 on 2019-03-26 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airtable_id', models.CharField(max_length=128)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('gender', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airtable_id', models.CharField(max_length=128)),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('year_founded', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=1028, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('alum', models.CharField(blank=True, max_length=128, null=True)),
                ('size', models.CharField(blank=True, max_length=32, null=True)),
                ('specialisation', models.CharField(blank=True, max_length=1028, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airtable_id', models.CharField(max_length=128)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('is_investment', models.BooleanField(default=0)),
                ('start_month', models.IntegerField(blank=True, null=True)),
                ('end_month', models.IntegerField(blank=True, null=True)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('ic_member', models.CharField(blank=True, max_length=1024, null=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='firms.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='firm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='firms.Firm'),
        ),
    ]
